sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast2-gpmc-image .
script:
  # the "yast-travis-cpp" script is included in the base yastdevel/cpp image
  # see https://github.com/yast/docker-yast-cpp/blob/master/yast-travis-cpp
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" yast2-gpmc-image yast-travis-cpp
