
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:

  Package:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/sle-15/sp3/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Package Build
      run: yast-ci-ruby -o package

  # downloading the Docker image takes some time so bundling several fast
  # checks into one job avoids that overhead
  Checks:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/sle-15/sp3/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Perl Syntax
      run: yast-ci-ruby -o perl_syntax

    - name: POT Check
      run: rake check:pot

