# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [ push, pull_request ]

jobs:

  Package:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distro: [ "tumbleweed" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Package Build
        run: yast-ci-ruby -o package

  # downloading the Docker image takes some time so bundling several fast
  # checks into one job avoids that overhead
  Checks:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distro: [ "tumbleweed" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Perl Syntax
        run: yast-ci-ruby -o perl_syntax

      - name: POT Check
        run: rake check:pot
